### ISSUE TITLE
Missing dep gir1.2-xapp-1.0 in deb package

### ISSUE THREAD

**Issue by cyberorg** [linuxmint/webapp-manager#10]
Launching webapp-manager on Ubuntu 20.04.1 gives out this error:

```Traceback (most recent call last):
  File "/usr/lib/webapp-manager/webapp-manager.py", line 19, in <module>
    gi.require_version('XApp', '1.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace XApp not available```

To enable launching of app install missing package.

`sudo apt install gir1.2-xapp-1.0`

**Comment by clefebvre** [comment]
fixed https://github.com/linuxmint/webapp-manager/commit/7f3348e711f9bf8975c5cad43390121103ff5049
