### ISSUE TITLE
Wrong range of Browser types list

### ISSUE THREAD

**Issue by hsbasu** [linuxmint/webapp-manager#114]
In `common.py`, line 46 is
```
BROWSER_TYPE_FIREFOX, BROWSER_TYPE_FIREFOX_FLATPAK, BROWSER_TYPE_CHROMIUM, BROWSER_TYPE_EPIPHANY, BROWSER_TYPE_FALKON = range(4)
```
This causes the following error:
```
Traceback (most recent call last):
  File "/home/himadri/Projects/Side_projects/my-repos/webapp-manager/usr/lib/webapp-manager/webapp-manager.py", line 20, in <module>
    from common import _async, idle, WebAppManager, Browser, download_favicon, ICONS_DIR, BROWSER_TYPE_FIREFOX
  File "/home/himadri/Projects/Side_projects/my-repos/webapp-manager/usr/lib/webapp-manager/common.py", line 46, in <module>
    BROWSER_TYPE_FIREFOX, BROWSER_TYPE_FIREFOX_FLATPAK, BROWSER_TYPE_CHROMIUM, BROWSER_TYPE_EPIPHANY, BROWSER_TYPE_FALKON = range(4)
ValueError: not enough values to unpack (expected 5, got 4)
```
The correction should be:
```
BROWSER_TYPE_FIREFOX, BROWSER_TYPE_FIREFOX_FLATPAK, BROWSER_TYPE_CHROMIUM, BROWSER_TYPE_EPIPHANY, BROWSER_TYPE_FALKON = range(5)
```

**Comment by Coeur-Noir** [comment]
Hi,

is this related ?

```
django@ASGARD:~$ webapp-manager 
django@ASGARD:~$ Traceback (most recent call last):
  File "/usr/lib/webapp-manager/webapp-manager.py", line 20, in <module>
    from common import _async, idle, WebAppManager, Browser, download_favicon, ICONS_DIR, BROWSER_TYPE_FIREFOX
  File "/usr/lib/webapp-manager/common.py", line 46, in <module>
    BROWSER_TYPE_FIREFOX, BROWSER_TYPE_FIREFOX_FLATPAK, BROWSER_TYPE_CHROMIUM, BROWSER_TYPE_EPIPHANY, BROWSER_TYPE_FALKON = range(4)
ValueError: not enough values to unpack (expected 5, got 4)
```
…when trying to launch.

v1.1.2 on Ubuntu 20.04 / Budgie.

**Comment by hsbasu** [comment]
Yes. The fix is to make `range(4)` to `range(5)` on line 46 of webapp-manager.py

**Comment by beevabeeva** [comment]
> Yes. The fix is to make `range(4)` to `range(5)` on line 46 of webapp-manager.py

line 46 of `common.py` (i.e `/usr/lib/webapp-manager/common.py`), not `webapp-manager.py` :)
