### ISSUE TITLE
Epiphany not working

### ISSUE THREAD

**Issue by tiotrom** [linuxmint/webapp-manager#15]
Adding an app through epiphany does nothing. Clicking OK does nothing.

**Comment by tiotrom** [comment]
Actually it seems that it adds it as an "app" but no dialogue to show that so I clicked OK 20 times and I ended up with 20 webapps :). But no webapp through epiphany works when you click it.

```
[tio@tio-pc ~]$ epiphany --application-mode  --profile="/home/tio/.local/share/ice/epiphany/epiphany-TROMepi5823"https://www.tromjaro.com/
--profile must be an existing directory when --application-mode is requested
```

**Comment by starsep** [comment]
can you try
> epiphany --application-mode  --profile="/home/tio/.local/share/ice/epiphany/epiphany-TROMepi5823" https://www.tromjaro.com/

(I added space after profile path)

**Comment by tiotrom** [comment]
Same error

**Comment by starsep** [comment]
I tried creating web app with epiphany myself, after clicking OK button:
``` python
Traceback (most recent call last):
  File "/usr/lib/webapp-manager/webapp-manager.py", line 297, in on_ok_button
    self.manager.create_webapp(name, url, icon, category, browser, isolate_profile, navbar)
  File "/usr/lib/webapp-manager/common.py", line 193, in create_webapp
    new_path = os.path.join(profile_path, "epiphany-%s.desktop" % codename)
UnboundLocalError: local variable 'profile_path' referenced before assignment
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_webapp-manager_webapp-manager.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/webapp-manager/webapp-manager.py", line 297, in on_ok_button
    self.manager.create_webapp(name, url, icon, category, browser, isolate_profile, navbar)
  File "/usr/lib/webapp-manager/common.py", line 193, in create_webapp
    new_path = os.path.join(profile_path, "epiphany-%s.desktop" % codename)
UnboundLocalError: local variable 'profile_path' referenced before assignment
```

**Comment by tiotrom** [comment]
Here's the .desktop file it creates:

```
[Desktop Entry]
Version=1.0
Name=TROMapps
Comment=TROMapps (Web App)
Exec=epiphany --application-mode  --profile="/home/tio/.local/share/ice/epiphany/epiphany-TROMapps9495"https://www.tromjaro.com/apps/
IceEpiphany=TROMapps9495
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=webapp-manager
Categories=GTK;WebApps;
MimeType=text/html;text/xml;application/xhtml_xml;
StartupWMClass=ICE-SSB-TROMapps9495
StartupNotify=true
```

**Comment by starsep** [comment]
Unfortunately I am not able to help.
From what I see in the source code profile dir for epiphany is just never created
Code crashes on trying to (?) moving desktop file to profile dir and then symlinking it
https://github.com/linuxmint/webapp-manager/blob/master/usr/lib/webapp-manager/common.py#L191

It just look that epiphany support is not ready yet.
