### ISSUE TITLE
webapp-manager not launching anymore after using a gif as image

### ISSUE THREAD

**Issue by djjldoooo** [linuxmint/webapp-manager#256]
I get this error message after adding an app with a gif image.

Traceback (most recent call last):
  File "/usr/lib/webapp-manager/webapp-manager.py", line 54, in activate
    window = WebAppManagerWindow(self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/webapp-manager/webapp-manager.py", line 215, in __init__
    self.load_webapps()
  File "/usr/lib/webapp-manager/webapp-manager.py", line 522, in load_webapps
    pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_size(webapp.icon, -1,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: gdk-pixbuf-error-quark: Certaines images de l’image GIF n’ont pas été chargées. (6)

The french part means:"Some GIF images have not been loaded."

**Comment by Nezzula** [comment]
If you just wish to run webapp-manager again just uninstall the app with the GIF as the icon and try running it,
the webapp-manager starts running again.

**Comment by daviii-lopes** [comment]
should it allow using gif as icon?
