### ISSUE TITLE
WebApp in Mint 22 doesn't create anything using Epiphany

### ISSUE THREAD

**Issue by europe1453** [linuxmint/webapp-manager#326]
When you're trying to create any app and choose the browser as Epiphany (system package), clicking on OK button (button became looks sticked down) produces an new applet instance at every click, but all of them doesn't work. Exploring system menu you can discover that these new applets have all empty parameters. Furthermore, they completely dissapear from system menu and from WebApps itself as well after reboot. So, using Epiphany as a target browser just doesn't create anything.

**Comment by henriquedesousa** [comment]
Exact same issues, they started right after I migrated from LM21 to LM22.

**Comment by TheCoolerMS3** [comment]
I found this bug myself and can confirm it's happening both on Mint 22.2 and Mint 21.3

**Comment by patlefort** [comment]
When clicking OK, it produce this error:

```
webapp-manager[285664]: Traceback (most recent call last):
webapp-manager[285664]:   File "/usr/lib/webapp-manager/webapp-manager.py", line 330, in on_ok_button
webapp-manager[285664]:     self.manager.create_webapp(name, desc, url, icon, category, browser, custom_parameters, isolate_profile, navbar,
webapp-manager[285664]:     ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webapp-manager[285664]:                                privatewindow)
webapp-manager[285664]:                                ^^^^^^^^^^^^^^
webapp-manager[285664]:   File "/usr/lib/webapp-manager/common.py", line 307, in create_webapp
webapp-manager[285664]:     shutil.copy(icon, new_icon)
webapp-manager[285664]:     ~~~~~~~~~~~^^^^^^^^^^^^^^^^
webapp-manager[285664]:   File "/usr/lib/python3.14/shutil.py", line 489, in copy
webapp-manager[285664]:     copyfile(src, dst, follow_symlinks=follow_symlinks)
webapp-manager[285664]:     ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webapp-manager[285664]:   File "/usr/lib/python3.14/shutil.py", line 313, in copyfile
webapp-manager[285664]:     with open(src, 'rb') as fsrc:
webapp-manager[285664]:          ~~~~^^^^^^^^^^^
webapp-manager[285664]: FileNotFoundError: [Errno 2] No such file or directory: 'webapp-manager'
```

There is a problem related to the icon.
