### ISSUE TITLE
python3-bs4 possibly a depend?

### ISSUE THREAD

**Issue by SwampRabbit** [linuxmint/webapp-manager#4]
Hello, first off, awesome work!

I believe that python3-bs4 is a dependency, which in turn installs python3-soupsieve as well.  Building with just python3-bs4 added as a depend seems to make the below go away, and it launches and work fine.

```$ Traceback (most recent call last):
  File "/usr/lib/webapp-manager/webapp-manager.py", line 22, in <module>
    from common import _async, idle, WebAppManager, STATUS_OK, download_favicon, ICONS_DIR
  File "/usr/lib/webapp-manager/common.py", line 192, in <module>
    import bs4
ModuleNotFoundError: No module named 'bs4'```

publicsuffix also shows up as a recommend during install, not fully sure if it is worthy of a depend or not.

**Comment by clefebvre** [comment]
Thanks this was indeed an issue. We no longer use bs4 though so it no longer needs fixing.

**Comment by SwampRabbit** [comment]
@clefebvre 

I think there is some residual scruff in there related to this.
I packaged what was committed this morning around the time you made the entry for 1.0.4.  I just got around to testing it.

Now without python3-bs4 this is the output when it fails to launch
```$ Traceback (most recent call last):
  File "/usr/lib/webapp-manager/webapp-manager.py", line 20, in <module>
    from common import _async, idle, WebAppManager, Browser, download_favicon, ICONS_DIR, BROWSER_TYPE_FIREFOX
  File "/usr/lib/webapp-manager/common.py", line 208, in <module>
    import bs4
ModuleNotFoundError: No module named 'bs4'
