### ISSUE TITLE
Plus button doesn't work when user doesn't have a browser installed in any of supported locations

### ISSUE THREAD

**Issue by starsep** [linuxmint/webapp-manager#5]
After clicking the plus button almost nothing happens - only visible change is that main app area gets extended.
It looks like some row is added to the GUI but that's it.

I use version 1.0.3 - from http://www.linuxmint.com/tmp/blog/3960/webapp-manager_1.0.3_all.deb

Traceback:
```
Traceback (most recent call last):
  File "/usr/lib/webapp-manager/webapp-manager.py", line 383, in on_browser_changed
    self.show_hide_browser_widgets()
  File "/usr/lib/webapp-manager/webapp-manager.py", line 386, in show_hide_browser_widgets
    browser = self.browser_combo.get_model()[self.browser_combo.get_active()][BROWSER_ID]
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 844, in __getitem__
    aiter = self._getiter(key)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 828, in _getiter
    raise IndexError("row index is out of bounds: %d" % key)
IndexError: row index is out of bounds: -1
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_webapp-manager_webapp-manager.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/webapp-manager/webapp-manager.py", line 383, in on_browser_changed
    self.show_hide_browser_widgets()
  File "/usr/lib/webapp-manager/webapp-manager.py", line 386, in show_hide_browser_widgets
    browser = self.browser_combo.get_model()[self.browser_combo.get_active()][BROWSER_ID]
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 844, in __getitem__
    aiter = self._getiter(key)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 828, in _getiter
    raise IndexError("row index is out of bounds: %d" % key)
IndexError: row index is out of bounds: -1
Traceback (most recent call last):
  File "/usr/lib/webapp-manager/webapp-manager.py", line 292, in on_add_button
    self.show_hide_browser_widgets()
  File "/usr/lib/webapp-manager/webapp-manager.py", line 386, in show_hide_browser_widgets
    browser = self.browser_combo.get_model()[self.browser_combo.get_active()][BROWSER_ID]
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 844, in __getitem__
    aiter = self._getiter(key)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 828, in _getiter
    raise IndexError("row index is out of bounds: %d" % key)
IndexError: row index is out of bounds: -1
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_webapp-manager_webapp-manager.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/webapp-manager/webapp-manager.py", line 292, in on_add_button
    self.show_hide_browser_widgets()
  File "/usr/lib/webapp-manager/webapp-manager.py", line 386, in show_hide_browser_widgets
    browser = self.browser_combo.get_model()[self.browser_combo.get_active()][BROWSER_ID]
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 844, in __getitem__
    aiter = self._getiter(key)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 828, in _getiter
    raise IndexError("row index is out of bounds: %d" % key)
IndexError: row index is out of bounds: -1
```

**Comment by starsep** [comment]
It's caused by an empty list of supported browsers.
I only have Firefox installed throught Flatpak: `/var/lib/flatpak/exports/bin/org.mozilla.firefox`.
After replacing `/usr/bin/firefox` with that path it works properly.

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/webapp-manager/commit/85b5872da9149cbf48d91799d8575fac6af06e88
