### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by GoSpursGoNL** [linuxmint/webapp-manager#55]
Hi, I upgraded Mint to 20.1. When I want to start the webapp-manager from the menu, nothing seems to happen. When I start from terminal, I see the following error. Running as root works fine but I assume that is not what I'm supposed to do.
```
File "/usr/lib/webapp-manager/webapp-manager.py", line 49, in activate
    window = WebAppManagerWindow(self)
  File "/usr/lib/webapp-manager/webapp-manager.py", line 200, in __init__
    self.load_webapps()
  File "/usr/lib/webapp-manager/webapp-manager.py", line 472, in load_webapps
    webapps = self.manager.get_webapps()
  File "/usr/lib/webapp-manager/common.py", line 114, in get_webapps
    for filename in os.listdir(APPS_DIR):
PermissionError: [Errno 13] Permission denied: '/home/myusername/.local/share/applications'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_webapp-manager_webapp-manager.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/webapp-manager/webapp-manager.py", line 49, in activate
    window = WebAppManagerWindow(self)
  File "/usr/lib/webapp-manager/webapp-manager.py", line 200, in __init__
    self.load_webapps()
  File "/usr/lib/webapp-manager/webapp-manager.py", line 472, in load_webapps
    webapps = self.manager.get_webapps()
  File "/usr/lib/webapp-manager/common.py", line 114, in get_webapps
    for filename in os.listdir(APPS_DIR):
PermissionError: [Errno 13] Permission denied: '/home/myusername/.local/share/applications'
```

**Comment by GoSpursGoNL** [comment]
Issue still occurs.

**Comment by hsbasu** [comment]
Can you please check permission of `/home/myusername/.local/share/applications` with `ls -la /home/myusername/.local/share/applications`?

**Comment by GoSpursGoNL** [comment]
Only works when running the command as root, otherwise permission denied.
Output:

```
total 20
drwx------  2 root   root   4096 Jan 18  2020 .
drwxr-xr-x 42 GoSpursGoNL GoSpursGoNL 4096 Mar 12 07:53 ..
-rw-r--r--  1 root   root     66 Jun  9  2018 mimeapps.list
-rw-r--r--  1 root   root     13 Jan 18  2020 mimeinfo.cache
-rw-r--r--  1 root   root    130 Aug 13  2016 userapp-xed-ZKFMLY.desktop
```

**Comment by hsbasu** [comment]
This is happening because of erroneous owner of the directory. It can be corrected by running `chown -R GoSpursGoNL:GoSpursGoNL /home/GoSpursGoNL/.local/share`

**Comment by GoSpursGoNL** [comment]
Thanks, it works!
